global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
global using WexTransaction.Domain.Entities;
global using WexTransaction.Domain.ValueObjects;
global using WexTransaction.Infra.Database.Data;
global using WexTransaction.Domain.Interfaces;
global using System.Data;
global using Dapper;
